documentary/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^title/add/$', views.title_add, name='title_add'),
    url(r'^title/show/$', views.title_show, name='title_show'),
    url(r'^title/batch/add/$', views.title_batch_add, name='title_batch_add'),
    url(r'^title/page/(\d+)$', views.title_page, name='title_page'),
    url(r'^site/add/$', views.site_add, name='site_add'),
    url(r'^site/show/(\d+)$', views.site_show, name='site_show'),
    url(r'^site/batch/add/$', views.site_batch_add, name='site_batch_add'),
    url(r'^error$', views.error, name='error'),
    url(r'^test/$',views.test,name='test'),
]

hobby/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    # Examples:
    url(r'^$','documentary.views.home', name='home'),
    url(r'^documentary/', include('documentary.urls', namespace="documentary")),
    # url(r'^$', 'hobby.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^about$',views.about, name='about'),
    url(r'^admin/', include(admin.site.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documentary/models.py
from django.db import models

# Create your models here.
class Title(models.Model):
    """docstring for title"""
    title_name = models.CharField(max_length=512)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title_name

class Author(models.Model):
    """docstring for Author"""
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)


class Site(models.Model):
    """docstring for site"""
    title = models.ForeignKey(Title)
    author = models.ForeignKey(Author)
    seed = models.CharField(max_length=1024)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s' % (self.seed)



class Staff(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    department = models.CharField(max_length=255)
    gender = models.CharField(max_length=4)
    photo = models.ImageField(upload_to='photo',null=True,blank=True)
    birthday = models.DateTimeField()
    join_time = models.DateTimeField()
    create_time = models.DateTimeField()
    update_time = models.DateTimeField(null=True)

    def __unicode__(self):
        return u'%s' % (self.name)

documentary/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect
from documentary.models import Title
from documentary.models import Author
from documentary.models import Site
from django.core.cache import cache
import requests


def paging_title(page):
    max_titles = 10
    total_titles = Title.objects.all()
    # get pages
    if (len(total_titles)%max_titles==0):
        total_pages = (len(total_titles)/max_titles)
    else:
        total_pages =(len(total_titles)/max_titles) +1

    if (page>total_pages):
        return HttpResponseRedirect('/documentary/error')

    last_page = total_pages
    # get pervious page
    if (page > 1):
        previous_page = page-1
    else:
        previous_page = 1
    # get next page
    if (page < last_page):
        next_page = page + 1
    else:
        next_page = last_page

    titles = total_titles[((page-1)*max_titles):(page*max_titles)]

    return titles, previous_page, next_page, total_pages

def get_file_path():
    return "/var/www/html/hobby/documentary/file/"

# Create your views here.
def home(request):
    page = 1
    titles, previous_page, next_page, total_pages = paging_title(page)
    return render(request,'index.html',{"titles": titles,"previous_page":previous_page,"current":page,"next_page":next_page,"total_pages":total_pages})

def index(request):
    page = 1
    titles, previous_page, next_page, total_pages = paging_title(page)
    return render(request,'documentary/index.html',{"titles": titles,"previous_page":previous_page,"current":page,"next_page":next_page,"total_pages":total_pages})

def title_add(request):
    return render(request, 'documentary/title_add.html')

def title_show(request):
    titles = Title.objects.all()
    return render(request,"documentary/title_show.html", {"titles": titles})

def title_batch_add(request):
    filename = get_file_path()+"title.txt"
    f = open(filename)
    lines = f.readlines()
    f.close()
    for line in lines:
        title = Title(title_name=line,)
        title.save()
    return HttpResponseRedirect('/documentary/title/show')

def title_page(request,page):
    page = int(page)
    titles, previous_page, next_page, total_pages = paging_title(page)
    return render(request,"documentary/title_page.html", {"titles": titles,"previous_page":previous_page,"current":page,"next_page":next_page,"total_pages":total_pages})

def site_add(request):
    return render(request,'documentary/site_add.html')

def site_show(request,title_id):
    title_id = int(title_id)
    sites = Site.objects.filter(title_id=title_id)
    title = Title.objects.get(id=title_id)
    return render(request,"documentary/site_show.html", {"sites": sites,"title":title})

def site_batch_add(request):
    to = Author.objects.get(name='to')
    filename = get_file_path()+"BT.txt"
    f = open(filename)
    lines = f.readlines()
    f.close()
    for line in lines:
        fields = line.split('\t')
        title = Title.objects.get(title_name=fields[(len(fields)-1)])
        for x in range(0,(len(fields)-1)):
            site = Site(title=title , author = to,seed=fields[x])
            site.save()

    return HttpResponseRedirect('/documentary/title/show')

def error(request):
    return render(request,"documentary/error.html")

def about(request):
    return render(request,"documentary/about.html")

def test(request):
#temp = req.json()['results'][0]
#pm25 = temp['pm25']
#temperature = temp['weather_data'][0]['temperature']
    cache.delete('weather')
    if not cache.get('weather'):
        URL = 'http://api.map.baidu.com/telematics/v3/weather?location=南京&output=json&ak=FK9mkfdQsloEngodbFl4FeY3'
        req = requests.get(URL)
        temp = req.json()['results'][0]
        pm25 = int(temp['pm25'])
        temperature = temp['weather_data'][0]['temperature']
       #pattern = re.compile(r'(\d+)')
       #temperature = re.findall(pattern,temperature)
       #temperature_low = temperature[1]
       #temperature_high = temperature[0]
       #data = {'pm25':pm25,'temperature_low':temperature_low,'temperature_high':temperature_high}
        data = {'pm25':pm25,'temperature':temperature}
        cache.set('weather',data,3600)
        data_cache = cache.get('weather')
    else:
        data_cache = cache.get('weather')
    return render(request,"documentary/test.html",{'data':data_cache})

hobby/views.py
# -*- codind:utf-8 -*-
from django.shortcuts import render

def about(request):
    return render(request,"about.html")

documentary/templates/about.html
{% extends "base.html" %}

{% block title %} 关于记录 - 记录 {% endblock %}

{% block content %}
<div class="container main">
    <div class="panel panel-info">
        <div class="panel-heading">记录</div>
            <div class="panel-body">
                只因为爱你
            </div>
        </div>
    </div>
</div>
{% endblock %}

documentary/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/gotop.css" %}">
    <link rel="stylesheet" href="{% static "css/error.css" %}">
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/gotop.js" %}"></script>
    <script>$(function() {if(($('.header').height()+$('.main').height()+$('.footer').height())<$('body').height())$('.main').css('height','100%');}); </script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="wo-go-top"><div class="wo-arrow"></div><div class="wo-stick"></div></div>
    <div class="navbar navbar-inverse navbar-fixed-top header">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target="#responsive-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'home' %}" class="navbar-brand" title="轮子首页"><strong>首页</strong></a>
            </div>
            <div class="collapse navbar-collapse" id="responsive-navbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'documentary:index' %}"><strong>纪录片</strong></a></li>
                </ul>
                {% block tab %}
                    <a href="{%  url  'documentary:title_add'  %}" class="hidden-xs btn btn-primary btn-sm navbar-btn navbar-right">添加标题</a>
                {% endblock %}
                <div class="profile navbar-right">
                    <ul class="nav navbar-nav">
                                         
                    </ul>
                </div>
                    <form action="#" class="navbar-form navbar-right">
                        <input type="text" placeholder="搜纪录片" class="form-control" name="query">
                        <button type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </form>
            </div>
        </div>
    </div>
    {% block content %}

    {% endblock %}
    <div class="footer">
        <div class="footer-about">
              <div class="container">
                     <div class="row">
                            <div class="col-md-6">
                                   <div class="row">
                                          <div class="col-md-3"><span><a href="{% url 'about' %}">关于记录</a></span></div>
                                   </div>       
                            </div>
                            <div class="col-md-6">
                                   <div class="row">
                                          <div class="col-md-4"></div>
                                          <div class="col-md-8"><span>Copyright © 记录 2015 All Rights Reserved </span></div>
                                    </div> 
                            </div>
                     </div>
              </div>
        </div>
</div>
</body>
</html>

documentary/templates/documentary/error.html
{% extends "base.html" %}

{% block title %} 404错误 - 记录 {% endblock %}
{% load staticfiles %}

{% block content %}
<div class="main" style="height:556px;">
    <div class="photo">
        <img class="error" alt="error" src='{% static "img/error.png" %}'>
        <img class="dialog" alt="dialog" src='{% static "img/dialog.png" %}'>
    </div>
    <div class="content">
        <div class="sorry">
            <div class="error_one">
                <img alt="404" src='{% static "img/404.png" %}'>
            </div>
            <div class="main_content">
                抱歉!  您访问的页面不存在
            </div>
            <div class="index">
                <a href="{% url 'home' %}">返回首页></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

documentary/templates/documentary/index.html
{% extends "base.html" %}

{% block title %} 纪录片 - 记录 {% endblock %}

{% block content %}
<div class="container main">
    <div class="row">
        {% for title in titles %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading" style="height:63px"><a href="{% url 'documentary:site_show' title.id %}">{{ title.title_name }}</a></div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-11">
            <nav class="pull-right">
                <ul class="pagination">
                    <li><a href="{% url 'documentary:title_page' previous_page %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    <li class="active"><a href="#">{{ current }}</a></li>
                    <li><a href="javascript:void(0)">共 {{ total_pages }} 页</a></li>
                    <li><a href="{% url 'documentary:title_page' next_page %}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    <li><a href="{% url 'documentary:title_show' %}">查看全部</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

documentary/templates/documentary/site_add.html
{% extends "base.html" %}

{% block title %} 批量加载种子 - 记录 {% endblock %}   

{% block tab %}
    <a href="{%  url  'documentary:site_add'  %}" class="hidden-xs btn btn-primary btn-sm navbar-btn navbar-right">添加种子</a>
{% endblock %}

{% block content %} 
<div class="container main">
    <a href="{% url 'documentary:site_batch_add' %}"><span class='glyphicon glyphicon-plus'></span>batch add site data</a>
</div>
{% endblock %}

documentary/templates/documentary/site_show.html
{% extends "base.html" %}

{% block title %} {{ title.title_name }} - 记录 {% endblock %}   

{% block content %} 
<div class="container main">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">{{ title.title_name }}</div>
                {% for site in sites %}
                    <div class="panel-body">
                        {{ site.seed }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

documentary/templates/documentary/test.html
<html>
<head>
</head>
<body>
{{data}}
</body>
</html>

documentary/templates/documentary/title_add.html
{% extends "base.html" %}

{% block title %} 批量加载标题 - 记录 {% endblock %}   

{% block content %} 
<div class="container main">
    <a href="{% url 'documentary:title_batch_add' %}"><span class='glyphicon glyphicon-plus'></span>batch add title data</a>
</div>
{% endblock %}

documentary/templates/documentary/title_page.html
{% extends "base.html" %}

{% block title %} 标题 - 记录 {% endblock %}   

{% block content %} 
<div class="container main">
    <div class="row">
    <div class="col-md-12">
    <div class="row">
        {% for title in titles %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading" style="height:63px"><a href="{% url 'documentary:site_show' title.id %}">{{ title.title_name }}</a></div>
            </div>
        </div>
        {% endfor %}
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-11">
            <nav class="pull-right">
                <ul class="pagination">
                    <li><a href="{% url 'documentary:title_page' previous_page %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    <li class="active"><a href="#">{{ current }}</a></li>
                    <li><a href="javascript:void(0)">共 {{ total_pages }} 页</a></li>
                    <li><a href="{% url 'documentary:title_page' next_page %}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    <li><a href="{% url 'documentary:title_show' %}">查看全部</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

documentary/templates/documentary/title_show.html
{% extends "base.html" %}

{% block title %} 标题 - 记录 {% endblock %}   

{% block tab %}
    <a href="{%  url  'documentary:site_add'  %}" class="hidden-xs btn btn-primary btn-sm navbar-btn navbar-right">添加种子</a>
{% endblock %}

{% block content %} 
<div class="container main">
    <div class="row">
        {% for title in titles %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading" style="height:63px"><a href="{% url 'documentary:site_show' title.id %}">{{ title.title_name }}</a></div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

documentary/templates/index.html
{% extends "base.html" %}

{% block title %} 首页 - 记录 {% endblock %}

{% block content %}
<div class="container main">
    <div class="row">
        {% for title in titles %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading" style="height:63px"><a href="{% url 'documentary:site_show' title.id %}">{{ title.title_name }}</a></div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-11">
            <nav class="pull-right">
                <ul class="pagination">
                    <li><a href="{% url 'documentary:title_page' previous_page %}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    <li class="active"><a href="#">{{ current }}</a></li>
                    <li><a href="javascript:void(0)">共 {{ total_pages }} 页</a></li>
                    <li><a href="{% url 'documentary:title_page' next_page %}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    <li><a href="{% url 'documentary:title_show' %}">查看全部</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>
{% endblock %}